// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#pragma once

#include <stdint.h>

#include "Maze.hpp"
#include "MazePlanner.hpp"
#include "MotionTypes.hpp"
#include "Movement.hpp"

namespace mtrn3100 {

struct Task43Config {
    CellCoordinate start;
    Direction startHeading;
    CellCoordinate goal;
};

// Deep Task 4.3 module: callers provide only start/goal and receive success or
// failure. Sensor interpretation, DFS bookkeeping, return, and shortest-route
// execution remain local to the implementation.
class AutonomousMapping {
public:
    AutonomousMapping(Movement& movement, const Task43Config& config);
    bool run();

private:
    enum class AdvanceResult : uint8_t {
        Arrived,
        Blocked,
        Fault,
    };

    bool exploreDepthFirst();
    void updateShortestPathProof();
    bool observeCurrentCell();
    bool inspectRearFromThreeWallStart();
    void applyObservation(Direction direction, ObservedEdge observation);
    bool findUnresolvedDirection(Direction& direction) const;
    bool faceDirection(Direction direction, bool fastProfile = false);
    bool confirmOpenAhead();
    AdvanceResult advance(Direction direction);
    bool directionToCell(uint8_t cell, Direction& direction) const;
    bool runShortestPath();
    void render();
    bool fail();

    Movement& mMovement;
    Pose mStartPose;
    uint8_t mGoalRow;
    uint8_t mGoalColumn;
    Maze mMaze;
    MazePlanner mPlanner;
    Pose mPose;
    uint8_t mDfsPath[MAZE_MAPPABLE_CELL_COUNT];
    uint8_t mDfsDepth = 0;
    bool mShortestPathProven = false;
    MappingPhase mPhase = MappingPhase::Explore;
};

}  // namespace mtrn3100
