// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#include "MappingObservation.hpp"

namespace mtrn3100 {

namespace {

// RESULT__RANGE_STATUS[7:4], documented by ST for the VL6180X.
constexpr uint8_t STATUS_EARLY_CONVERGENCE = 6;
constexpr uint8_t STATUS_MAX_CONVERGENCE = 7;
constexpr uint8_t STATUS_NO_TARGET_IGNORE = 8;
constexpr uint8_t STATUS_MAX_SNR = 11;
constexpr uint8_t STATUS_RAW_RANGE_UNDERFLOW = 12;
constexpr uint8_t STATUS_RAW_RANGE_OVERFLOW = 13;
constexpr uint8_t STATUS_RANGE_UNDERFLOW = 14;
constexpr uint8_t STATUS_RANGE_OVERFLOW = 15;

}  // namespace

ObservedEdge classifyMappingRange(
    bool rangeValid,
    uint16_t distanceMm,
    uint8_t rangeStatus,
    float wallMaximumMm,
    float openMinimumMm) {
    if (rangeValid) {
        if (distanceMm <= wallMaximumMm) return ObservedEdge::Wall;
        if (distanceMm >= openMinimumMm) return ObservedEdge::Open;
        return ObservedEdge::Unknown;
    }

    // These are completed optical measurements—not transport failures. ST's
    // VL6180X status guidance identifies 6/7/8 as no-target outcomes and
    // 13/15 as a target beyond the usable range. A max-SNR result also votes
    // Open when its completed range is beyond the normal open threshold.
    // Five independent results must still agree before Movement promotes the
    // direction to Open.
    if (rangeStatus == STATUS_EARLY_CONVERGENCE
        || rangeStatus == STATUS_MAX_CONVERGENCE
        || rangeStatus == STATUS_NO_TARGET_IGNORE
        || (rangeStatus == STATUS_MAX_SNR
            && distanceMm >= openMinimumMm)
        || rangeStatus == STATUS_RAW_RANGE_OVERFLOW
        || rangeStatus == STATUS_RANGE_OVERFLOW) {
        return ObservedEdge::Open;
    }

    // Underflow indicates a target at approximately 0–10 mm. It is safer and
    // more accurate to record that direction as blocked than as unknown.
    if (rangeStatus == STATUS_RAW_RANGE_UNDERFLOW
        || rangeStatus == STATUS_RANGE_UNDERFLOW) {
        return ObservedEdge::Wall;
    }
    return ObservedEdge::Unknown;
}

}  // namespace mtrn3100
