// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#include "Maze.hpp"

namespace mtrn3100 {

namespace {

constexpr uint8_t EDGE_BITS = 2;
constexpr uint8_t EDGE_MASK = 0x03U;

}  // namespace

Maze::Maze() {
    reset();
}

void Maze::reset() {
    for (uint8_t cell = 0; cell < MAZE_CELL_COUNT; ++cell) {
        mEdges[cell] = 0;
    }
    for (uint8_t byte = 0; byte < sizeof(mVisited); ++byte) {
        mVisited[byte] = 0;
    }
    for (uint8_t byte = 0; byte < sizeof(mTraversed); ++byte) {
        mTraversed[byte] = 0;
    }
    mVisitedCount = 0;

    // The outer perimeter and the four non-playable corner triominoes are
    // authoritative arena geometry. Every edge that cannot lead to another
    // mappable cell starts as Wall; all other edges remain Unknown.
    for (uint8_t row = 0; row < MAZE_ROWS; ++row) {
        for (uint8_t column = 0; column < MAZE_COLUMNS; ++column) {
            for (uint8_t rawDirection = 0;
                 rawDirection < 4U;
                 ++rawDirection) {
                const Direction direction = directionFromIndex(rawDirection);
                uint8_t adjacentRow = 0;
                uint8_t adjacentColumn = 0;
                if (!isMappable(row, column)
                    || !neighbour(
                        row,
                        column,
                        direction,
                        adjacentRow,
                        adjacentColumn)) {
                    writeEdge(row, column, direction, EdgeState::Wall);
                }
            }
        }
    }
}

bool Maze::inBounds(uint8_t row, uint8_t column) {
    return row < MAZE_ROWS && column < MAZE_COLUMNS;
}

bool Maze::isMappable(uint8_t row, uint8_t column) {
    return isMappableCell(row, column);
}

uint8_t Maze::indexOf(uint8_t row, uint8_t column) {
    return inBounds(row, column)
         ? static_cast<uint8_t>(row * MAZE_COLUMNS + column)
         : INVALID_CELL;
}

uint8_t Maze::rowOf(uint8_t cellIndex) {
    return cellIndex < MAZE_CELL_COUNT
         ? static_cast<uint8_t>(cellIndex / MAZE_COLUMNS)
         : INVALID_CELL;
}

uint8_t Maze::columnOf(uint8_t cellIndex) {
    return cellIndex < MAZE_CELL_COUNT
         ? static_cast<uint8_t>(cellIndex % MAZE_COLUMNS)
         : INVALID_CELL;
}

bool Maze::neighbour(
    uint8_t row,
    uint8_t column,
    Direction direction,
    uint8_t& neighbourRow,
    uint8_t& neighbourColumn) {
    if (!isMappable(row, column) || !isValidDirection(direction)) return false;

    neighbourRow = row;
    neighbourColumn = column;
    switch (direction) {
        case Direction::North:
            if (row == 0) return false;
            --neighbourRow;
            return isMappable(neighbourRow, neighbourColumn);
        case Direction::East:
            if (column + 1U >= MAZE_COLUMNS) return false;
            ++neighbourColumn;
            return isMappable(neighbourRow, neighbourColumn);
        case Direction::South:
            if (row + 1U >= MAZE_ROWS) return false;
            ++neighbourRow;
            return isMappable(neighbourRow, neighbourColumn);
        case Direction::West:
            if (column == 0) return false;
            --neighbourColumn;
            return isMappable(neighbourRow, neighbourColumn);
    }
    return false;
}

EdgeState Maze::edge(
    uint8_t row,
    uint8_t column,
    Direction direction) const {
    if (!inBounds(row, column) || !isValidDirection(direction)) {
        return EdgeState::Conflict;
    }
    if (!isMappable(row, column)) return EdgeState::Wall;

    const uint8_t shift = directionIndex(direction) * EDGE_BITS;
    return static_cast<EdgeState>(
        (mEdges[indexOf(row, column)] >> shift) & EDGE_MASK);
}

EdgeState Maze::mergeObservations(EdgeState first, EdgeState second) {
    if (first == EdgeState::Conflict || second == EdgeState::Conflict) {
        return EdgeState::Conflict;
    }
    if (first == EdgeState::Unknown) return second;
    if (second == EdgeState::Unknown || first == second) return first;
    return EdgeState::Conflict;
}

bool Maze::observeEdge(
    uint8_t row,
    uint8_t column,
    Direction direction,
    EdgeState observation) {
    if (!isMappable(row, column)
        || !isValidDirection(direction)
        || !isValidEdgeState(observation)) {
        return false;
    }

    uint8_t adjacentRow = 0;
    uint8_t adjacentColumn = 0;
    const bool hasNeighbour = neighbour(
        row, column, direction, adjacentRow, adjacentColumn);

    // The 9x9 coordinate limits are known independently of the physical
    // walls. A lidar can legitimately see open space beyond an absent outer
    // wall, but the robot must still treat that direction as outside its map.
    if (!hasNeighbour) {
        writeEdge(row, column, direction, EdgeState::Wall);
        return true;
    }

    const EdgeState current = edge(row, column, direction);
    const EdgeState reciprocal = edge(
        adjacentRow,
        adjacentColumn,
        oppositeDirection(direction));

    // Physical traversal is stronger than lidar evidence. Preserve it as Open
    // while still allowing non-traversed optical edges to become Conflict and
    // be rescanned from another orientation.
    if (wasTraversed(row, column, direction)) {
        return observation == EdgeState::Unknown
            || observation == EdgeState::Open;
    }

    // A Conflict records one contradictory scan. A later complete consensus
    // scan is allowed to resolve an interior edge; otherwise one noisy batch
    // would permanently disconnect the planner's graph.
    const bool resolvingConflict = current == EdgeState::Conflict
        && reciprocal == EdgeState::Conflict
        && (observation == EdgeState::Open
            || observation == EdgeState::Wall);
    EdgeState merged;
    if (resolvingConflict) {
        merged = observation;
    } else {
        merged = mergeObservations(current, observation);
    }
    if (!resolvingConflict) {
        merged = mergeObservations(
            merged,
            reciprocal);
    }

    writeEdge(row, column, direction, merged);
    writeEdge(
        adjacentRow,
        adjacentColumn,
        oppositeDirection(direction),
        merged);
    return merged != EdgeState::Conflict;
}

bool Maze::confirmOpen(uint8_t row, uint8_t column, Direction direction) {
    if (!isMappable(row, column) || !isValidDirection(direction)) return false;

    uint8_t adjacentRow = 0;
    uint8_t adjacentColumn = 0;
    if (!neighbour(row, column, direction, adjacentRow, adjacentColumn)) {
        // Logical grid limits remain authoritative even if there is no
        // physical perimeter wall in an open test area.
        writeEdge(row, column, direction, EdgeState::Wall);
        return false;
    }

    writeEdge(row, column, direction, EdgeState::Open);
    writeEdge(
        adjacentRow,
        adjacentColumn,
        oppositeDirection(direction),
        EdgeState::Open);
    markTraversed(row, column, direction);
    markTraversed(
        adjacentRow,
        adjacentColumn,
        oppositeDirection(direction));
    return true;
}

bool Maze::wasTraversed(
    uint8_t row,
    uint8_t column,
    Direction direction) const {
    if (!isMappable(row, column) || !isValidDirection(direction)) return false;
    const uint16_t bitIndex = static_cast<uint16_t>(indexOf(row, column)) * 4U
                            + directionIndex(direction);
    const uint8_t byte = static_cast<uint8_t>(bitIndex >> 3);
    const uint8_t bit = static_cast<uint8_t>(1U << (bitIndex & 0x07U));
    return (mTraversed[byte] & bit) != 0;
}

bool Maze::markVisited(uint8_t row, uint8_t column) {
    if (!isMappable(row, column)) return false;

    const uint8_t cell = indexOf(row, column);
    const uint8_t byte = cell >> 3;
    const uint8_t bit = static_cast<uint8_t>(1U << (cell & 0x07U));
    if ((mVisited[byte] & bit) != 0) return false;

    mVisited[byte] |= bit;
    ++mVisitedCount;
    return true;
}

bool Maze::isVisited(uint8_t row, uint8_t column) const {
    if (!isMappable(row, column)) return false;

    const uint8_t cell = indexOf(row, column);
    const uint8_t byte = cell >> 3;
    const uint8_t bit = static_cast<uint8_t>(1U << (cell & 0x07U));
    return (mVisited[byte] & bit) != 0;
}

uint8_t Maze::visitedCount() const {
    return mVisitedCount;
}

bool Maze::isComplete() const {
    for (uint8_t row = 0; row < MAZE_ROWS; ++row) {
        for (uint8_t column = 0; column < MAZE_COLUMNS; ++column) {
            if (!isMappable(row, column)) continue;
            for (uint8_t rawDirection = 0; rawDirection < 4; ++rawDirection) {
                const EdgeState state = edge(
                    row,
                    column,
                    directionFromIndex(rawDirection));
                if (state == EdgeState::Unknown
                    || state == EdgeState::Conflict) {
                    return false;
                }
            }
        }
    }
    return true;
}

void Maze::writeEdge(
    uint8_t row,
    uint8_t column,
    Direction direction,
    EdgeState state) {
    const uint8_t shift = directionIndex(direction) * EDGE_BITS;
    const uint8_t shiftedMask = static_cast<uint8_t>(EDGE_MASK << shift);
    const uint8_t shiftedState = static_cast<uint8_t>(
        static_cast<uint8_t>(state) << shift);
    uint8_t& cell = mEdges[indexOf(row, column)];
    cell = static_cast<uint8_t>((cell & static_cast<uint8_t>(~shiftedMask))
                              | shiftedState);
}

void Maze::markTraversed(
    uint8_t row,
    uint8_t column,
    Direction direction) {
    const uint16_t bitIndex = static_cast<uint16_t>(indexOf(row, column)) * 4U
                            + directionIndex(direction);
    const uint8_t byte = static_cast<uint8_t>(bitIndex >> 3);
    const uint8_t bit = static_cast<uint8_t>(1U << (bitIndex & 0x07U));
    mTraversed[byte] |= bit;
}

}  // namespace mtrn3100
