// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#pragma once

#include <stdint.h>

#include "NavigationTypes.hpp"

namespace mtrn3100 {

// Each cell stores four two-bit EdgeState values in NESW order. Edge updates
// are mirrored into adjacent cells so callers cannot create one-way passages.
class Maze {
public:
    Maze();

    void reset();

    static bool inBounds(uint8_t row, uint8_t column);
    static bool isMappable(uint8_t row, uint8_t column);
    static uint8_t indexOf(uint8_t row, uint8_t column);
    static uint8_t rowOf(uint8_t cellIndex);
    static uint8_t columnOf(uint8_t cellIndex);
    static bool neighbour(
        uint8_t row,
        uint8_t column,
        Direction direction,
        uint8_t& neighbourRow,
        uint8_t& neighbourColumn);

    EdgeState edge(uint8_t row, uint8_t column, Direction direction) const;

    // Returns false when the observation contradicts established map data.
    // Contradictory sides are retained as Conflict rather than guessed away.
    bool observeEdge(
        uint8_t row,
        uint8_t column,
        Direction direction,
        EdgeState observation);

    // A completed physical traversal is definitive evidence of an open edge.
    // It repairs weaker sensor observations on both sides of the passage.
    bool confirmOpen(uint8_t row, uint8_t column, Direction direction);
    bool wasTraversed(uint8_t row, uint8_t column, Direction direction) const;

    // Returns true only when this call visits the cell for the first time.
    bool markVisited(uint8_t row, uint8_t column);
    bool isVisited(uint8_t row, uint8_t column) const;
    uint8_t visitedCount() const;
    bool isComplete() const;

private:
    static EdgeState mergeObservations(EdgeState first, EdgeState second);
    void writeEdge(
        uint8_t row,
        uint8_t column,
        Direction direction,
        EdgeState state);
    void markTraversed(
        uint8_t row,
        uint8_t column,
        Direction direction);

    uint8_t mEdges[MAZE_CELL_COUNT];
    uint8_t mVisited[(MAZE_CELL_COUNT + 7U) / 8U];
    uint8_t mTraversed[(MAZE_CELL_COUNT * 4U + 7U) / 8U];
    uint8_t mVisitedCount;
};

static_assert(
    sizeof(Maze) == MAZE_CELL_COUNT
                  + (MAZE_CELL_COUNT + 7U) / 8U
                  + (MAZE_CELL_COUNT * 4U + 7U) / 8U
                  + 1U,
    "Maze storage must remain packed and fixed-size");

}  // namespace mtrn3100
