import type { StoryChapter } from '../types/showcase';

export const chapters: StoryChapter[] = [
  {
    id: 'meet',
    number: '01',
    eyebrow: 'UNSW Robotics',
    title: 'Meet the Micromouse',
    body: 'An educational twist on the famous Micromouse competition robot - a compact autonomous robot designed to sense maze walls, plan a route, and navigate it under closed-loop control.',
    metric: '180',
    metricLabel: 'mm maze class',
  },
  {
    id: 'inside',
    number: '02',
    eyebrow: 'Exploded architecture',
    title: 'A Custom Robot for Education',
    body: 'Sensors, power, drive, and control hardware are connected with custom PCBs held together in a student-designed chassis. Select any part to inspect it.',
    metric: '20',
    metricLabel: 'key systems',
  },
  {
    id: 'sense',
    number: '03',
    eyebrow: 'Perception',
    title: 'Multiple Perception Sensors',
    body: 'Three range sensors read nearby walls while encoders measure wheel motion and the IMU tracks yaw rotation.',
    metric: '03',
    metricLabel: 'sensor types',
  },
  {
    id: 'think',
    number: '04',
    eyebrow: 'Control pipeline',
    title: 'From Sensors to Motion',
    body: 'Sensor signals are fused into a pose estimate using an Extended Kalman Filter, compared against a path, then converted into precise motor commands.',
    metric: '04',
    metricLabel: 'control stages',
  },
  {
    id: 'move',
    number: '05',
    eyebrow: 'Path following',
    title: 'Real Time Maze Exploration',
    body: 'A Pure Pursuit algorithm uses a look-ahead target to pull the robot through the maze while continuous corrections keep the chassis centred.',
    metric: '60',
    metricLabel: 'updates / sec',
  },
  {
    id: 'explore',
    number: '06',
    eyebrow: 'Free inspection',
    title: "Explore the Digital Twin",
    body: "Orbit the micromouse's digital twin, zoom into the stack, or use the component index to focus on a subsystem.",
    metric: '360°',
    metricLabel: 'inspection',
  },
];
