// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#include "AutonomousMapping.hpp"

#include "RobotGeometry.hpp"

namespace mtrn3100 {

namespace {

EdgeState mapState(ObservedEdge observation) {
    if (observation == ObservedEdge::Open) return EdgeState::Open;
    if (observation == ObservedEdge::Wall) return EdgeState::Wall;
    return EdgeState::Unknown;
}

// observeWalls() itself is bounded to about 1.1 seconds. Starting the final
// batch before 8.5 seconds therefore still leaves margin below ten seconds.
constexpr uint32_t SENSOR_RETRY_WINDOW_MS = 8500;
// A successful first scan must leave room for one 7.25 s turn and one final
// 1.2 s side-lidar scan inside a ten-second inspection episode.
constexpr uint32_t INSPECTION_TURN_START_DEADLINE_MS = 1250;
constexpr uint32_t NO_CELL_PROGRESS_MS = 9000;
constexpr uint8_t MAX_MAPPING_PASSES = 3;
constexpr uint8_t MAX_RECALIBRATION_ATTEMPTS = 3;

}  // namespace

AutonomousMapping::AutonomousMapping(
    Movement& movement,
    const Task43Config& config)
    : mMovement(movement),
      mStartPose(poseFromCartesian(config.start, config.startHeading)),
      mGoalRow(internalRowFromY(config.goal.y)),
      mGoalColumn(config.goal.x),
      mPose(mStartPose) {}

bool AutonomousMapping::run() {
    if (!Maze::isMappable(mStartPose.row, mStartPose.column)
        || !isValidDirection(mStartPose.heading)
        || !Maze::isMappable(mGoalRow, mGoalColumn)) {
        return fail();
    }

    mMaze.reset();
    mPose = mStartPose;
    mPhase = MappingPhase::Explore;
    mShortestPathProven = false;
    mDfsDepth = 1;
    mDfsPath[0] = Maze::indexOf(mPose.row, mPose.column);
    mMaze.markVisited(mPose.row, mPose.column);
    render();

    if (!observeCurrentCell()) return fail();
    updateShortestPathProof();
    uint8_t mappingPass = 1;
    while (true) {
        if (!exploreDepthFirst()) return fail();
        if (mShortestPathProven
            || (mMaze.visitedCount() == MAZE_MAPPABLE_CELL_COUNT
                && mMaze.isComplete())) {
            break;
        }

        // A fresh pass can recover from a false optical wall, but it must not
        // become an endless reset loop when no sensor can expose a frontier.
        if (mMaze.visitedCount() <= 1
            || mappingPass >= MAX_MAPPING_PASSES) {
            return fail();
        }
        if (mPose.row != mStartPose.row
            || mPose.column != mStartPose.column
            || !faceDirection(mStartPose.heading)) {
            return fail();
        }
        ++mappingPass;
        mMaze.reset();
        mShortestPathProven = false;
        mPhase = MappingPhase::Explore;
        mDfsDepth = 1;
        mDfsPath[0] = Maze::indexOf(mPose.row, mPose.column);
        mMaze.markVisited(mPose.row, mPose.column);
        render();
        if (!observeCurrentCell()) return fail();
        updateShortestPathProof();
    }

    // Iterative DFS finishes at its root, so this is both a phase marker for
    // the demonstrator and a defensive pose check.
    mPhase = MappingPhase::ReturnToStart;
    if (mPose.row != mStartPose.row
        || mPose.column != mStartPose.column
        || !faceDirection(mStartPose.heading)) {
        return fail();
    }
    render();

    for (uint8_t attempt = 0;
         attempt < MAX_RECALIBRATION_ATTEMPTS;
         ++attempt) {
        if (mMovement.recalibrateAtCurrentHeading()) break;
        if (attempt + 1U < MAX_RECALIBRATION_ATTEMPTS) {
            mMovement.settle(100);
        }
    }
    if (!mPlanner.computeDistances(
            mMaze, mGoalRow, mGoalColumn, false)
        || mPlanner.distanceAt(mPose.row, mPose.column)
            == MazePlanner::UNREACHABLE) {
        return fail();
    }

    mPhase = MappingPhase::ShortestRun;
    render();
    if (!runShortestPath()) return fail();

    mPhase = MappingPhase::Done;
    mMovement.stop();
    render();
    return true;
}

bool AutonomousMapping::exploreDepthFirst() {
    uint32_t lastProgressAt = millis();
    while (true) {
        if (millis() - lastProgressAt >= NO_CELL_PROGRESS_MS) return false;

        Direction nextDirection = mPose.heading;
        if (!mShortestPathProven
            && mPlanner.chooseOpenUnvisitedNeighbour(
                mMaze, mPose, nextDirection)) {
            if (mDfsDepth >= MAZE_MAPPABLE_CELL_COUNT) {
                return false;
            }
            const AdvanceResult result = advance(nextDirection);
            if (result == AdvanceResult::Fault) return false;
            if (result == AdvanceResult::Blocked) {
                // The newly observed wall/conflict is map progress and this
                // edge is no longer eligible for confirmed-open planning.
                lastProgressAt = millis();
                updateShortestPathProof();
                continue;
            }
            mDfsPath[mDfsDepth++] = Maze::indexOf(mPose.row, mPose.column);
            if (!observeCurrentCell()) return false;
            lastProgressAt = millis();
            updateShortestPathProof();
            continue;
        }

        if (mDfsDepth == 1) return true;

        Direction parentDirection = mPose.heading;
        const uint8_t parent = mDfsPath[mDfsDepth - 2U];
        if (!directionToCell(parent, parentDirection)
            || advance(parentDirection) != AdvanceResult::Arrived
            || Maze::indexOf(mPose.row, mPose.column) != parent) {
            return false;
        }
        --mDfsDepth;
        lastProgressAt = millis();
        render();
    }
}

void AutonomousMapping::updateShortestPathProof() {
    if (mShortestPathProven) return;

    if (!mPlanner.hasProvenShortestPath(
            mMaze,
            mStartPose.row,
            mStartPose.column,
            mGoalRow,
            mGoalColumn)) {
        return;
    }

    // Stop opening new DFS branches. The existing parent stack remains a
    // confirmed-open route back to the start, so exploreDepthFirst() will now
    // unwind it before the shortest-path run begins.
    mShortestPathProven = true;
    mPhase = MappingPhase::ReturnToStart;
    render();
}

bool AutonomousMapping::observeCurrentCell() {
    const uint32_t startedAt = millis();
    while (millis() - startedAt < SENSOR_RETRY_WINDOW_MS) {
        WallObservation observation;
        if (!mMovement.observeWalls(observation)) {
            mMovement.settle(100);
            continue;
        }

        applyObservation(mPose.heading, observation.front);
        applyObservation(directionLeftOf(mPose.heading), observation.left);
        applyObservation(directionRightOf(mPose.heading), observation.right);

        const bool atStart = mDfsDepth == 1U
            && mPose.row == mStartPose.row
            && mPose.column == mStartPose.column;
        const bool threeVisibleWalls =
            observation.front == ObservedEdge::Wall
            && observation.left == ObservedEdge::Wall
            && observation.right == ObservedEdge::Wall;
        if (atStart && threeVisibleWalls) {
            // The only possible exit is behind the robot. Inspect it before the
            // lengthy three-wall landmark calibration consumes the ordinary
            // unresolved-edge turn deadline.
            return inspectRearFromThreeWallStart();
        }

        // A three-wall cell is a rare absolute-heading landmark. Movement uses
        // the side lidars as sweep-clearance checks and the front lidar's local
        // range minimum to square the chassis before refreshing gyro bias.
        if (threeVisibleWalls
            && !mMovement.alignAndRecalibrateFromThreeWalls()) {
            return false;
        }

        Direction unresolved = mPose.heading;
        if (!findUnresolvedDirection(unresolved)) {
            render();
            return true;
        }
        // Aim a sensor that produced known evidence in this batch at the
        // unresolved edge. This lets either side lidar replace a failed front
        // lidar without assuming that an unread edge is Open.
        Direction inspectionHeading = unresolved;
        if (observation.left != ObservedEdge::Unknown) {
            inspectionHeading = directionRightOf(unresolved);
        } else if (observation.right != ObservedEdge::Unknown) {
            inspectionHeading = directionLeftOf(unresolved);
        }
        if (millis() - startedAt >= INSPECTION_TURN_START_DEADLINE_MS) {
            render();
            return true;
        }
        if (!faceDirection(inspectionHeading)) return false;

        // The inspection turn is specifically to put a side lidar on the edge
        // the front lidar could not resolve. Take that batch now, then return;
        // starting another turn would open a second recovery window.
        WallObservation inspection;
        if (mMovement.observeWalls(inspection)) {
            applyObservation(mPose.heading, inspection.front);
            applyObservation(
                directionLeftOf(mPose.heading), inspection.left);
            applyObservation(
                directionRightOf(mPose.heading), inspection.right);
            render();
        }
        return true;
    }
    // Keep any unresolved edges Unknown. Confirmed partial observations still
    // let DFS make the best safe attempt available from this cell.
    return true;
}

bool AutonomousMapping::inspectRearFromThreeWallStart() {
    const Direction rearDirection = oppositeDirection(mPose.heading);
    if (!faceDirection(rearDirection)) return false;

    // Start a fresh sensor budget after the 180-degree turn. Reusing the
    // original inspection deadline is what previously left the rear Unknown.
    const uint32_t startedAt = millis();
    while (millis() - startedAt < SENSOR_RETRY_WINDOW_MS) {
        WallObservation rearObservation;
        if (!mMovement.observeWalls(rearObservation)) {
            mMovement.settle(100);
            continue;
        }

        applyObservation(mPose.heading, rearObservation.front);
        applyObservation(
            directionLeftOf(mPose.heading), rearObservation.left);
        applyObservation(
            directionRightOf(mPose.heading), rearObservation.right);

        EdgeState rearState = mMaze.edge(
            mPose.row, mPose.column, rearDirection);
        if (rearState == EdgeState::Open || rearState == EdgeState::Wall) {
            render();
            return true;
        }

        // If the front lidar could not resolve the old rear edge, put a side
        // lidar that did return known evidence onto it for one bounded recovery
        // scan, matching the normal unresolved-edge strategy.
        Direction inspectionHeading = rearDirection;
        if (rearObservation.left != ObservedEdge::Unknown) {
            inspectionHeading = directionRightOf(rearDirection);
        } else if (rearObservation.right != ObservedEdge::Unknown) {
            inspectionHeading = directionLeftOf(rearDirection);
        } else {
            mMovement.settle(100);
            continue;
        }

        if (!faceDirection(inspectionHeading)) return false;
        WallObservation inspection;
        if (!mMovement.observeWalls(inspection)) return false;
        applyObservation(mPose.heading, inspection.front);
        applyObservation(directionLeftOf(mPose.heading), inspection.left);
        applyObservation(directionRightOf(mPose.heading), inspection.right);

        rearState = mMaze.edge(mPose.row, mPose.column, rearDirection);
        render();
        return rearState == EdgeState::Open || rearState == EdgeState::Wall;
    }

    render();
    return false;
}

void AutonomousMapping::applyObservation(
    Direction direction,
    ObservedEdge observation) {
    if (observation == ObservedEdge::Unknown) return;

    // Maze owns evidence precedence: physically traversed edges remain Open;
    // contradictory optical evidence becomes Conflict and is rescanned.
    mMaze.observeEdge(
        mPose.row, mPose.column, direction, mapState(observation));
}

bool AutonomousMapping::findUnresolvedDirection(Direction& direction) const {
    for (uint8_t preference = 0; preference < 4; ++preference) {
        Direction candidate = mPose.heading;
        if (preference == 1) candidate = directionLeftOf(mPose.heading);
        if (preference == 2) candidate = directionRightOf(mPose.heading);
        if (preference == 3) candidate = oppositeDirection(mPose.heading);

        uint8_t adjacentRow = 0;
        uint8_t adjacentColumn = 0;
        if (!Maze::neighbour(
                mPose.row,
                mPose.column,
                candidate,
                adjacentRow,
                adjacentColumn)) {
            continue;
        }
        const EdgeState state = mMaze.edge(
            mPose.row, mPose.column, candidate);
        if (state == EdgeState::Unknown || state == EdgeState::Conflict) {
            direction = candidate;
            return true;
        }
    }
    return false;
}

bool AutonomousMapping::faceDirection(
    Direction direction,
    bool fastProfile) {
    if (!isValidDirection(direction)) return false;
    uint8_t quarterTurns = static_cast<uint8_t>(
        (directionIndex(direction) + 4U - directionIndex(mPose.heading)) & 0x03U);

    if (quarterTurns == 0) return true;

    // One 180-degree target avoids two separate retry windows. Movement's
    // existing turn controller already has a seven-second deadline.
    const bool turnLeft = quarterTurns == 3;
    const float angleDeg = turnLeft
                         ? 90.0f
                         : static_cast<float>(quarterTurns) * 90.0f;
    const bool turned = fastProfile
        ? (turnLeft
            ? mMovement.rotateLeftTask41(angleDeg)
            : mMovement.rotateRightTask41(angleDeg))
        : (turnLeft
            ? mMovement.rotateLeft(angleDeg)
            : mMovement.rotateRight(angleDeg));
    if (!turned) return false;
    mPose.heading = direction;
    return true;
}

bool AutonomousMapping::confirmOpenAhead() {
    const uint32_t startedAt = millis();
    while (millis() - startedAt < SENSOR_RETRY_WINDOW_MS) {
        WallObservation observation;
        if (!mMovement.observeWalls(observation)) {
            mMovement.settle(100);
            continue;
        }
        if (observation.front == ObservedEdge::Wall) {
            // A successful physical traversal is stronger evidence than a
            // later optical contradiction. This keeps DFS backtracking from
            // being rejected by one bad stationary scan. An untraversed edge
            // is updated to Conflict instead, so it will not be entered.
            if (mMaze.wasTraversed(
                    mPose.row, mPose.column, mPose.heading)) {
                return true;
            }
            mMaze.observeEdge(
                mPose.row,
                mPose.column,
                mPose.heading,
                EdgeState::Wall);
            return false;
        }
        if (observation.front == ObservedEdge::Open) return true;
    }
    // This edge was already classified Open before advance() was called. If
    // only the front lidar is unavailable, use that existing evidence and make
    // the physical attempt instead of waiting forever.
    return mMaze.edge(
        mPose.row, mPose.column, mPose.heading) == EdgeState::Open;
}

AutonomousMapping::AdvanceResult AutonomousMapping::advance(
    Direction direction) {
    if (!isValidDirection(direction)
        || !Maze::isMappable(mPose.row, mPose.column)) {
        return AdvanceResult::Fault;
    }
    if (mMaze.edge(mPose.row, mPose.column, direction) != EdgeState::Open) {
        return AdvanceResult::Blocked;
    }
    if (!faceDirection(direction)) return AdvanceResult::Fault;
    if (!confirmOpenAhead()) {
        // A fresh wall is a map update, not a reason to abandon the run. The
        // caller replans and chooses another branch/path.
        return AdvanceResult::Blocked;
    }

    uint8_t nextRow = 0;
    uint8_t nextColumn = 0;
    if (!Maze::neighbour(
            mPose.row,
            mPose.column,
            direction,
            nextRow,
            nextColumn)) {
        return AdvanceResult::Fault;
    }

    const uint8_t oldRow = mPose.row;
    const uint8_t oldColumn = mPose.column;
    // moveOneCell() already maximises safe retries inside its bounded encoder
    // window. Never start a fresh full cell after that window expires.
    const CellMoveResult moveResult = mMovement.moveOneCell();
    if (moveResult == CellMoveResult::Timeout
        && !mMaze.wasTraversed(oldRow, oldColumn, direction)) {
        // Neither wheel moved far enough to lose the pose. Quarantine this
        // candidate as Conflict and let DFS try another confirmed-open edge.
        // Conflict remains optimistic for shortest-path proof, unlike a
        // fabricated permanent wall.
        mMaze.observeEdge(
            oldRow, oldColumn, direction, EdgeState::Wall);
        return AdvanceResult::Blocked;
    }
    if (moveResult != CellMoveResult::Arrived) {
        return AdvanceResult::Fault;
    }

    if (!mMaze.confirmOpen(oldRow, oldColumn, direction)) {
        return AdvanceResult::Fault;
    }
    mPose.row = nextRow;
    mPose.column = nextColumn;
    mPose.heading = direction;
    mMaze.markVisited(mPose.row, mPose.column);
    mMovement.adjusttWall();
    render();
    return AdvanceResult::Arrived;
}

bool AutonomousMapping::directionToCell(
    uint8_t cell,
    Direction& direction) const {
    if (cell >= MAZE_CELL_COUNT
        || !Maze::isMappable(Maze::rowOf(cell), Maze::columnOf(cell))) {
        return false;
    }
    for (uint8_t index = 0; index < 4; ++index) {
        const Direction candidate = directionFromIndex(index);
        uint8_t adjacentRow = 0;
        uint8_t adjacentColumn = 0;
        if (Maze::neighbour(
                mPose.row,
                mPose.column,
                candidate,
                adjacentRow,
                adjacentColumn)
            && Maze::indexOf(adjacentRow, adjacentColumn) == cell) {
            direction = candidate;
            return true;
        }
    }
    return false;
}

bool AutonomousMapping::runShortestPath() {
    if (!mPlanner.computeDistances(
            mMaze, mGoalRow, mGoalColumn, false)) {
        return false;
    }

    // Build and validate the complete confirmed route before starting the fast
    // physical run. Unlike the compile-time command string, these commands are
    // derived solely from the map made during this run.
    Direction route[MAZE_MAPPABLE_CELL_COUNT];
    uint8_t routeLength = 0;
    Pose plannedPose = mPose;
    while (plannedPose.row != mGoalRow
           || plannedPose.column != mGoalColumn) {
        if (routeLength >= MAZE_MAPPABLE_CELL_COUNT) return false;

        Direction direction = plannedPose.heading;
        if (!mPlanner.chooseDescendingDirection(
                mMaze, plannedPose, direction, false)
            || mMaze.edge(
                plannedPose.row,
                plannedPose.column,
                direction) != EdgeState::Open) {
            return false;
        }

        uint8_t nextRow = 0;
        uint8_t nextColumn = 0;
        if (!Maze::neighbour(
                plannedPose.row,
                plannedPose.column,
                direction,
                nextRow,
                nextColumn)
            || !Maze::isMappable(nextRow, nextColumn)) {
            return false;
        }

        route[routeLength++] = direction;
        plannedPose.row = nextRow;
        plannedPose.column = nextColumn;
        plannedPose.heading = direction;
    }

    // This mirrors command-string mode: fast 90/180-degree turns, followed by
    // one continuous encoder/IMU-controlled move for each run of 'f' cells.
    // Logical pose is committed only after the complete physical segment says
    // it arrived; a partial timeout therefore becomes a fault, not fake map
    // progress.
    uint8_t routeIndex = 0;
    while (routeIndex < routeLength) {
        const Direction direction = route[routeIndex];
        uint8_t straightCells = 1;
        while (routeIndex + straightCells < routeLength
               && route[routeIndex + straightCells] == direction) {
            ++straightCells;
        }

        if (!faceDirection(direction, true)
            || !mMovement.moveForward(
                static_cast<float>(straightCells)
                    * geometry::CELL_SIZE_MM)) {
            return false;
        }
        mMovement.settle(100);

        for (uint8_t cell = 0; cell < straightCells; ++cell) {
            uint8_t nextRow = 0;
            uint8_t nextColumn = 0;
            if (mMaze.edge(
                    mPose.row, mPose.column, direction) != EdgeState::Open
                || !Maze::neighbour(
                    mPose.row,
                    mPose.column,
                    direction,
                    nextRow,
                    nextColumn)) {
                return false;
            }
            mPose.row = nextRow;
            mPose.column = nextColumn;
            mPose.heading = direction;
            mMaze.markVisited(mPose.row, mPose.column);
        }

        routeIndex = static_cast<uint8_t>(routeIndex + straightCells);
        render();
    }
    return mPose.row == mGoalRow && mPose.column == mGoalColumn;
}

void AutonomousMapping::render() {
    mMovement.showMap(
        mMaze,
        mPose,
        mStartPose,
        mGoalRow,
        mGoalColumn,
        mPhase);
}

bool AutonomousMapping::fail() {
    mPhase = MappingPhase::Fault;
    mMovement.stop();
    render();
    return false;
}

}  // namespace mtrn3100
