// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#include "MazePlanner.hpp"

namespace mtrn3100 {

MazePlanner::MazePlanner() {
    for (uint8_t cell = 0; cell < MAZE_CELL_COUNT; ++cell) {
        mDistance[cell] = UNREACHABLE;
    }
}

bool MazePlanner::computeDistances(
    const Maze& maze,
    uint8_t destinationRow,
    uint8_t destinationColumn,
    bool optimistic) {
    for (uint8_t cell = 0; cell < MAZE_CELL_COUNT; ++cell) {
        mDistance[cell] = UNREACHABLE;
    }
    if (!Maze::isMappable(destinationRow, destinationColumn)) return false;

    // The BFS queue is needed only while flooding the completed map. Keeping
    // the 69-byte mappable-cell workspace local releases it immediately after
    // this call instead of consuming scarce Nano SRAM for the entire run.
    uint8_t queue[MAZE_MAPPABLE_CELL_COUNT];
    uint8_t head = 0;
    uint8_t tail = 0;
    const uint8_t destination = Maze::indexOf(
        destinationRow, destinationColumn);
    mDistance[destination] = 0;
    queue[tail++] = destination;

    while (head < tail) {
        const uint8_t cell = queue[head++];
        const uint8_t row = Maze::rowOf(cell);
        const uint8_t column = Maze::columnOf(cell);

        for (uint8_t index = 0; index < 4; ++index) {
            const Direction direction = directionFromIndex(index);
            if (!isTraversable(maze.edge(row, column, direction), optimistic)) {
                continue;
            }

            uint8_t adjacentRow = 0;
            uint8_t adjacentColumn = 0;
            if (!Maze::neighbour(
                    row,
                    column,
                    direction,
                    adjacentRow,
                    adjacentColumn)) {
                continue;
            }

            const uint8_t adjacent = Maze::indexOf(
                adjacentRow, adjacentColumn);
            if (mDistance[adjacent] != UNREACHABLE) continue;

            mDistance[adjacent] = static_cast<uint8_t>(mDistance[cell] + 1U);
            queue[tail++] = adjacent;
        }
    }
    return true;
}

uint8_t MazePlanner::distanceAt(uint8_t row, uint8_t column) const {
    if (!Maze::isMappable(row, column)) return UNREACHABLE;
    return mDistance[Maze::indexOf(row, column)];
}

bool MazePlanner::hasProvenShortestPath(
    const Maze& maze,
    uint8_t startRow,
    uint8_t startColumn,
    uint8_t destinationRow,
    uint8_t destinationColumn) {
    if (!Maze::isMappable(startRow, startColumn)
        || !Maze::isMappable(destinationRow, destinationColumn)) {
        return false;
    }

    // Treating unresolved edges as open gives a lower bound: completing the
    // map cannot reveal a route shorter than this optimistic distance.
    if (!computeDistances(
            maze, destinationRow, destinationColumn, true)) {
        return false;
    }
    const uint8_t optimisticDistance = distanceAt(startRow, startColumn);

    // A route made entirely from confirmed-open edges is executable and is an
    // upper bound on the true shortest distance. Compute it second so a true
    // result leaves mDistance ready for confirmed-only route selection.
    if (!computeDistances(
            maze, destinationRow, destinationColumn, false)) {
        return false;
    }
    const uint8_t confirmedDistance = distanceAt(startRow, startColumn);

    return confirmedDistance != UNREACHABLE
        && confirmedDistance == optimisticDistance;
}

bool MazePlanner::chooseDescendingDirection(
    const Maze& maze,
    const Pose& pose,
    Direction& direction,
    bool optimistic) const {
    if (!Maze::isMappable(pose.row, pose.column)
        || !isValidDirection(pose.heading)) {
        return false;
    }

    const uint8_t currentDistance = distanceAt(pose.row, pose.column);
    if (currentDistance == UNREACHABLE || currentDistance == 0) return false;

    for (uint8_t index = 0; index < 4; ++index) {
        const Direction candidate = preference(pose.heading, index);
        if (!isTraversable(
                maze.edge(pose.row, pose.column, candidate), optimistic)) {
            continue;
        }

        uint8_t adjacentRow = 0;
        uint8_t adjacentColumn = 0;
        if (!Maze::neighbour(
                pose.row,
                pose.column,
                candidate,
                adjacentRow,
                adjacentColumn)) {
            continue;
        }
        if (distanceAt(adjacentRow, adjacentColumn)
            != static_cast<uint8_t>(currentDistance - 1U)) {
            continue;
        }

        direction = candidate;
        return true;
    }
    return false;
}

bool MazePlanner::chooseOpenUnvisitedNeighbour(
    const Maze& maze,
    const Pose& pose,
    Direction& direction) const {
    if (!Maze::isMappable(pose.row, pose.column)
        || !isValidDirection(pose.heading)) {
        return false;
    }

    for (uint8_t index = 0; index < 4; ++index) {
        const Direction candidate = preference(pose.heading, index);
        if (maze.edge(pose.row, pose.column, candidate) != EdgeState::Open) {
            continue;
        }

        uint8_t adjacentRow = 0;
        uint8_t adjacentColumn = 0;
        if (!Maze::neighbour(
                pose.row,
                pose.column,
                candidate,
                adjacentRow,
                adjacentColumn)) {
            continue;
        }
        if (maze.isVisited(adjacentRow, adjacentColumn)) continue;

        direction = candidate;
        return true;
    }
    return false;
}

bool MazePlanner::isTraversable(EdgeState state, bool optimistic) {
    return state == EdgeState::Open
        || (optimistic
            && (state == EdgeState::Unknown
                || state == EdgeState::Conflict));
}

Direction MazePlanner::preference(
    Direction heading,
    uint8_t preferenceIndex) {
    switch (preferenceIndex) {
        case 0: return heading;
        case 1: return directionLeftOf(heading);
        case 2: return directionRightOf(heading);
        default: return oppositeDirection(heading);
    }
}

}  // namespace mtrn3100
