// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#pragma once

#include <stdint.h>

namespace mtrn3100 {

constexpr uint8_t MAZE_ROWS = 9;
constexpr uint8_t MAZE_COLUMNS = 9;
constexpr uint8_t MAZE_CELL_COUNT = MAZE_ROWS * MAZE_COLUMNS;
constexpr uint8_t MAZE_EXCLUDED_CELL_COUNT = 12;
constexpr uint8_t MAZE_MAPPABLE_CELL_COUNT =
    MAZE_CELL_COUNT - MAZE_EXCLUDED_CELL_COUNT;
constexpr uint8_t INVALID_CELL = UINT8_MAX;

enum class Direction : uint8_t {
    North = 0,  // decreasing row
    East = 1,   // increasing column
    South = 2,  // increasing row
    West = 3,   // decreasing column
};

enum class EdgeState : uint8_t {
    Unknown = 0,
    Open = 1,
    Wall = 2,
    Conflict = 3,
};

struct Pose {
    uint8_t row;
    uint8_t column;
    Direction heading;
};

// Public Task 4.3 coordinates use the conventional Cartesian maze frame:
// (0,0) is south-west, x grows East, and y grows North. Pose remains the
// compact internal display/storage frame where row zero is at the top.
struct CellCoordinate {
    uint8_t x;
    uint8_t y;
};

constexpr uint8_t directionIndex(Direction direction) {
    return static_cast<uint8_t>(direction);
}

constexpr bool isValidDirection(Direction direction) {
    return directionIndex(direction) < 4U;
}

constexpr bool isValidEdgeState(EdgeState state) {
    return static_cast<uint8_t>(state) < 4U;
}

constexpr Direction directionFromIndex(uint8_t index) {
    return static_cast<Direction>(index & 0x03U);
}

constexpr Direction directionRightOf(Direction direction) {
    return directionFromIndex(directionIndex(direction) + 1U);
}

constexpr Direction directionLeftOf(Direction direction) {
    return directionFromIndex(directionIndex(direction) + 3U);
}

constexpr Direction oppositeDirection(Direction direction) {
    return directionFromIndex(directionIndex(direction) + 2U);
}

constexpr bool isValidCoordinate(CellCoordinate coordinate) {
    return coordinate.x < MAZE_COLUMNS && coordinate.y < MAZE_ROWS;
}

// The physical Task 4.3 arena omits an L-shaped triomino at every corner.
// Equivalently, a cell is excluded when its Manhattan distance from its
// nearest corner is zero or one. This predicate is computed rather than
// stored, so the topology costs no Nano SRAM.
constexpr uint8_t distanceToNearestBoundary(uint8_t value, uint8_t size) {
    return value < static_cast<uint8_t>(size - 1U - value)
         ? value
         : static_cast<uint8_t>(size - 1U - value);
}

constexpr bool isExcludedCoordinate(CellCoordinate coordinate) {
    return isValidCoordinate(coordinate)
        && static_cast<uint8_t>(
               distanceToNearestBoundary(coordinate.x, MAZE_COLUMNS)
             + distanceToNearestBoundary(coordinate.y, MAZE_ROWS)) <= 1U;
}

constexpr bool isMappableCoordinate(CellCoordinate coordinate) {
    return isValidCoordinate(coordinate) && !isExcludedCoordinate(coordinate);
}

// Internal rows are vertically inverted relative to Cartesian y, but the
// distance to the nearest boundary (and therefore the exclusion rule) is the
// same in both coordinate systems.
constexpr bool isMappableCell(uint8_t row, uint8_t column) {
    return row < MAZE_ROWS
        && column < MAZE_COLUMNS
        && static_cast<uint8_t>(
               distanceToNearestBoundary(row, MAZE_ROWS)
             + distanceToNearestBoundary(column, MAZE_COLUMNS)) > 1U;
}

constexpr uint8_t internalRowFromY(uint8_t y) {
    return static_cast<uint8_t>(MAZE_ROWS - 1U - y);
}

constexpr Pose poseFromCartesian(
    CellCoordinate coordinate,
    Direction heading) {
    return Pose{internalRowFromY(coordinate.y), coordinate.x, heading};
}

static_assert(
    MAZE_ROWS == 9 && MAZE_COLUMNS == 9 && MAZE_CELL_COUNT == 81,
    "The Task 4.3 arena topology is defined for a 9x9 grid");
static_assert(
    MAZE_MAPPABLE_CELL_COUNT == 69,
    "The four excluded corner triominoes must leave 69 mappable cells");
static_assert(
    isExcludedCoordinate(CellCoordinate{0, 0})
        && isExcludedCoordinate(CellCoordinate{0, 1})
        && isExcludedCoordinate(CellCoordinate{1, 0})
        && isExcludedCoordinate(CellCoordinate{0, 8})
        && isExcludedCoordinate(CellCoordinate{0, 7})
        && isExcludedCoordinate(CellCoordinate{1, 8})
        && isExcludedCoordinate(CellCoordinate{8, 0})
        && isExcludedCoordinate(CellCoordinate{8, 1})
        && isExcludedCoordinate(CellCoordinate{7, 0})
        && isExcludedCoordinate(CellCoordinate{8, 8})
        && isExcludedCoordinate(CellCoordinate{8, 7})
        && isExcludedCoordinate(CellCoordinate{7, 8}),
    "All four corner triominoes must be excluded");
static_assert(
    isMappableCoordinate(CellCoordinate{1, 1})
        && isMappableCoordinate(CellCoordinate{1, 7})
        && isMappableCoordinate(CellCoordinate{7, 1})
        && isMappableCoordinate(CellCoordinate{7, 7}),
    "Diagonal cells inside the corner triominoes must remain mappable");
static_assert(sizeof(Direction) == 1, "Direction must remain one byte");
static_assert(sizeof(EdgeState) == 1, "EdgeState must remain one byte");
static_assert(sizeof(Pose) == 3, "Pose must remain a compact three-byte value");
static_assert(
    sizeof(CellCoordinate) == 2,
    "A Cartesian maze coordinate must remain two bytes");

}  // namespace mtrn3100
