import type { ComponentDefinition, ComponentId } from '../types/showcase';

export const componentDefinitions: ComponentDefinition[] = [
  {
    id: 'chassis',
    meshName: 'chassis',
    title: 'Chassis',
    shortLabel: 'CHASSIS',
    description: 'The rigid mechanical frame that keeps the electronics, sensors, and wheel alignment repeatable.',
    accent: '#f2f0e8',
    explodeOffset: [0, -0.22, 0],
  },
  {
    id: 'bottom_pcb',
    meshName: 'bottom_pcb',
    title: 'Bottom PCB',
    shortLabel: 'PCB LOW',
    description: 'Carries the lower-level power and drive hardware in the stacked electronics assembly.',
    accent: '#59c878',
    explodeOffset: [0, 0.34, 0],
  },
  {
    id: 'top_pcb',
    meshName: 'top_pcb',
    title: 'Top PCB',
    shortLabel: 'PCB TOP',
    description: 'Supports the upper control, sensing, display, and interconnection hardware.',
    accent: '#45b86a',
    explodeOffset: [0, 0.64, 0],
  },
  {
    id: 'battery',
    meshName: 'battery',
    title: 'Battery',
    shortLabel: 'BATTERY',
    description: 'A low-mounted energy store that keeps the centre of gravity close to the track.',
    accent: '#d8ff65',
    explodeOffset: [0, 0.22, 0.48],
  },
  {
    id: 'power_switch',
    meshName: 'power_switch',
    title: 'Power switch',
    shortLabel: 'SWITCH',
    description: 'Provides a deliberate physical disconnect between the battery and robot electronics.',
    accent: '#ffb800',
    explodeOffset: [0.52, 0.42, 0.58],
  },
  {
    id: 'microcontroller',
    meshName: 'microcontroller',
    title: 'Microcontroller',
    shortLabel: 'MCU',
    description: 'Runs sensing, pose estimation, path following, and the motor control loop.',
    accent: '#ffb800',
    explodeOffset: [-0.24, 0.92, 0.08],
  },
  {
    id: 'imu',
    meshName: 'imu',
    title: 'Inertial measurement unit',
    shortLabel: 'IMU',
    description: 'Measures angular motion so the estimated heading stays stable through fast turns.',
    accent: '#9edcff',
    explodeOffset: [0.42, 0.92, 0.04],
  },
  {
    id: 'tof_left',
    meshName: 'tof_left',
    title: 'Left ToF sensor',
    shortLabel: 'TOF +90',
    description: 'Measures the wall to the robot\'s left along the positive ninety-degree axis.',
    accent: '#45e6ff',
    explodeOffset: [-0.82, 0.52, -0.2],
  },
  {
    id: 'tof_front',
    meshName: 'tof_front',
    title: 'Front ToF sensor',
    shortLabel: 'TOF 0',
    description: 'Measures the wall directly ahead along the robot\'s zero-degree forward axis.',
    accent: '#45e6ff',
    explodeOffset: [0, 0.52, -0.78],
  },
  {
    id: 'tof_right',
    meshName: 'tof_right',
    title: 'Right ToF sensor',
    shortLabel: 'TOF -90',
    description: 'Measures the wall to the robot\'s right along the negative ninety-degree axis.',
    accent: '#45e6ff',
    explodeOffset: [0.82, 0.52, -0.2],
  },
  {
    id: 'oled_display',
    meshName: 'oled_display',
    title: 'OLED display',
    shortLabel: 'OLED',
    description: 'Shows live robot status, sensor readings, and diagnostic information during operation.',
    accent: '#70b7ff',
    explodeOffset: [0, 0.86, 0.52],
  },
  {
    id: 'motor_driver',
    meshName: 'motor_driver',
    title: 'Dual motor driver',
    shortLabel: 'DRIVER',
    description: 'Converts low-power control signals into bidirectional current for both drive motors.',
    accent: '#ff7a45',
    explodeOffset: [0.48, 0.68, 0.24],
  },
  {
    id: 'motor_left',
    meshName: 'motor_left',
    title: 'Left motor',
    shortLabel: 'MOTOR L',
    description: 'A compact geared drive independently controlled for turning and acceleration.',
    accent: '#ff7a45',
    explodeOffset: [-0.62, 0.05, 0.12],
  },
  {
    id: 'motor_right',
    meshName: 'motor_right',
    title: 'Right motor',
    shortLabel: 'MOTOR R',
    description: 'Pairs with the left motor for differential steering through the maze.',
    accent: '#ff7a45',
    explodeOffset: [0.62, 0.05, 0.12],
  },
  {
    id: 'encoder_left',
    meshName: 'encoder_left',
    title: 'Left encoder',
    shortLabel: 'ENC L',
    description: 'Counts left wheel rotation for distance, velocity, and pose estimation.',
    accent: '#d8ff65',
    explodeOffset: [-0.72, 0.15, 0.25],
  },
  {
    id: 'encoder_right',
    meshName: 'encoder_right',
    title: 'Right encoder',
    shortLabel: 'ENC R',
    description: 'Counts right wheel rotation and exposes mismatch between commanded and actual motion.',
    accent: '#d8ff65',
    explodeOffset: [0.72, 0.15, 0.25],
  },
  {
    id: 'wheel_left',
    meshName: 'wheel_left',
    title: 'Left wheel',
    shortLabel: 'WHEEL L',
    description: 'A high-grip contact patch that turns precise motor motion into track speed.',
    accent: '#f2f0e8',
    explodeOffset: [-0.92, 0, 0.06],
  },
  {
    id: 'wheel_right',
    meshName: 'wheel_right',
    title: 'Right wheel',
    shortLabel: 'WHEEL R',
    description: 'The right-side drive contact, independently accelerated for differential steering.',
    accent: '#f2f0e8',
    explodeOffset: [0.92, 0, 0.06],
  },
  {
    id: 'ball_caster_front',
    meshName: 'ball_caster_front',
    title: 'Front ball caster',
    shortLabel: 'CASTER F',
    description: 'A low-friction metal support that stabilises the chassis ahead of the drive axle.',
    accent: '#d7dadd',
    explodeOffset: [0, -0.2, -0.62],
  },
  {
    id: 'ball_caster_rear',
    meshName: 'ball_caster_rear',
    title: 'Rear ball caster',
    shortLabel: 'CASTER R',
    description: 'A second metal support that keeps the chassis level behind the drive axle.',
    accent: '#d7dadd',
    explodeOffset: [0, -0.2, 0.62],
  },
];

export const componentById = Object.fromEntries(
  componentDefinitions.map((component) => [component.id, component]),
) as Record<ComponentId, ComponentDefinition>;

export const requiredMeshNames = [
  'mouse_root',
  ...componentDefinitions.map((component) => component.meshName),
];
