// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#pragma once

#include <stdint.h>

#include "MotionTypes.hpp"

namespace mtrn3100 {

// Classifies one completed VL6180X ranging result. Transport failures never
// call this function because Lidar advances its observation sequence only
// after all status/value/interrupt-clear transactions succeed.
ObservedEdge classifyMappingRange(
    bool rangeValid,
    uint16_t distanceMm,
    uint8_t rangeStatus,
    float wallMaximumMm,
    float openMinimumMm);

}  // namespace mtrn3100
