// AI-AUTHORED CODE: Generated by OpenAI Codex for the MTRN3100 project.
#pragma once

#include <stdint.h>

#include "Maze.hpp"

namespace mtrn3100 {

class MazePlanner {
public:
    static constexpr uint8_t UNREACHABLE = UINT8_MAX;

    MazePlanner();

    // Floods outward from the destination. Optimistic mode permits unresolved
    // Unknown and Conflict edges, giving a lower bound on routes through the
    // unfinished map.
    bool computeDistances(
        const Maze& maze,
        uint8_t destinationRow,
        uint8_t destinationColumn,
        bool optimistic = false);

    uint8_t distanceAt(uint8_t row, uint8_t column) const;

    // A confirmed-open route is provably shortest when its length matches the
    // optimistic lower bound obtained by allowing every unresolved edge. The
    // final distance field is left in confirmed-only mode for callers that
    // immediately want to follow the proven route.
    bool hasProvenShortestPath(
        const Maze& maze,
        uint8_t startRow,
        uint8_t startColumn,
        uint8_t destinationRow,
        uint8_t destinationColumn);

    // Both selectors prefer straight, left, right, then back relative to the
    // supplied pose. The descending selector must use the same optimistic
    // mode as the preceding computeDistances() call.
    bool chooseDescendingDirection(
        const Maze& maze,
        const Pose& pose,
        Direction& direction,
        bool optimistic = false) const;
    bool chooseOpenUnvisitedNeighbour(
        const Maze& maze,
        const Pose& pose,
        Direction& direction) const;

private:
    static bool isTraversable(EdgeState state, bool optimistic);
    static Direction preference(Direction heading, uint8_t preferenceIndex);

    uint8_t mDistance[MAZE_CELL_COUNT];
};

static_assert(
    sizeof(MazePlanner) == MAZE_CELL_COUNT,
    "MazePlanner must contain only its persistent distance array");

}  // namespace mtrn3100
